// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZHAIEuGzH0lJoHWxB-86VTU3ZOj4PJz0',
    appId: '1:122821072700:web:17afd23ccb14de7e2e3039',
    messagingSenderId: '122821072700',
    projectId: 'attandanceapp-a7c51',
    authDomain: 'attandanceapp-a7c51.firebaseapp.com',
    storageBucket: 'attandanceapp-a7c51.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAprDMwGqdzplZvYzgkJOzZ2Zg4twukIHY',
    appId: '1:122821072700:android:3e53a7c744b771692e3039',
    messagingSenderId: '122821072700',
    projectId: 'attandanceapp-a7c51',
    storageBucket: 'attandanceapp-a7c51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa0CI7NB1VPYOVdzUBt7LFMLh-GEPy4F8',
    appId: '1:122821072700:ios:996b5d7b99ae6e332e3039',
    messagingSenderId: '122821072700',
    projectId: 'attandanceapp-a7c51',
    storageBucket: 'attandanceapp-a7c51.appspot.com',
    iosClientId: '122821072700-4n88ltfq44heri0pb8d7ek3di7l0l3m4.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendancesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa0CI7NB1VPYOVdzUBt7LFMLh-GEPy4F8',
    appId: '1:122821072700:ios:996b5d7b99ae6e332e3039',
    messagingSenderId: '122821072700',
    projectId: 'attandanceapp-a7c51',
    storageBucket: 'attandanceapp-a7c51.appspot.com',
    iosClientId: '122821072700-4n88ltfq44heri0pb8d7ek3di7l0l3m4.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendancesApp',
  );
}
